src/StsServerIdentity/Controllers/SetLanguageController.cs
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace StsServerIdentity.Controllers
{
    public class SetLanguageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl, string returnUrlForLanguageSwitch)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return Redirect(returnUrlForLanguageSwitch);
        }
    }
}

src/StsServerIdentity/Views/Shared/_Layout.cshtml
@using StsServerIdentity.Resources
@inject LocService SharedLocalizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>StsServerIdentity</title>
    <link rel="stylesheet" href="~/css/vendor.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/fontawesome-free-5.4.1-web/css/all.min.css" asp-append-version="true"  />
</head>
<body>
    <div>
        <nav class="bg-dark mb-4 navbar navbar-dark navbar-expand-md">
            <a asp-controller="Home" asp-action="Index" class="navbar-brand">
                <em>ID4 Identity</em>
            </a>
            <button aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#topNavbarCollapse" data-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="topNavbarCollapse">
                <ul class="mr-auto navbar-nav">
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" class="nav-link">@SharedLocalizer.GetLocalizedHtmlString("HOME")</a>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </nav>

    </div>

    <div class="container body-content">
        @RenderBody()
       
    </div>

    <footer>
        <hr />
        <nav class="navbar transparent navbar-inverse">
            <p>&copy; 2018 - StsServerIdentity</p>

            @await Html.PartialAsync("_SelectLanguagePartial")
        </nav>
    </footer>

    <script src="~/js/vendor.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

src/StsServerIdentity/Views/Shared/_ScopeListItem.cshtml
@using StsServerIdentity.Resources
@inject LocService SharedLocalizer
@model StsServerIdentity.Models.ScopeViewModel

<li class="list-group-item">
    <label>
        <input class="consent-scopecheck big_checkbox" type="checkbox" name="ScopesConsented"
               id="scopes_@Model.Name" value="@Model.Name" checked="@Model.Checked" disabled="@Model.Required" />

        @if (Model.Required)
        {
            <input type="hidden" name="ScopesConsented" value="@Model.Name" />
        }
        <strong class="consent-middle">@SharedLocalizer.GetLocalizedHtmlStringAllowNull(Model.DisplayName)</strong>
        @if (Model.Emphasize)
        {
            <span class="fas fa-exclamation consent-middle"></span>
        }
    </label>

    @if (Model.Required)
    {
        <span class="consent-middle"><em>@SharedLocalizer.GetLocalizedHtmlString("CONSENT_REQUIRED")</em></span>
    }
    @if (Model.Description != null)
    {
        <div class="">
            <label for="scopes_@Model.Name">@SharedLocalizer.GetLocalizedHtmlStringAllowNull(Model.Description)</label>
        </div>
    }

</li>

src/StsServerIdentity/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
@using StsServerIdentity.Resources
@inject LocService SharedLocalizer
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    @{ 
        var location = new Uri($"{Context.Request.Scheme}://{Context.Request.Host}{Context.Request.Path}{Context.Request.QueryString}");

        var url = location.AbsoluteUri;
        var returnUrlForLanguageSwitch = Context.Request.Path;

        if (Context.Request.QueryString.HasValue)
        {
            returnUrlForLanguageSwitch = $"{Context.Request.Path}{Context.Request.QueryString.Value}";
        }
    }
    <form class="form-inline" id="selectLanguage" asp-controller="SetLanguage" asp-action="SetLanguage" asp-route-returnUrl="@returnUrlForLanguageSwitch" method="post" role="form">
        <label class="form-label paddingright5px" >@SharedLocalizer.GetLocalizedHtmlString("LANGUAGE"): </label>
        <div class="input-group">

            <select class="custom-select" name="culture" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
            <input type="hidden" name="returnUrlForLanguageSwitch" id="returnUrlForLanguageSwitch" value="@url"/>
            <div class="input-group-append">
                <button type="submit" class="btn btn-outline-secondary">@SharedLocalizer.GetLocalizedHtmlString("SAVE")</button>
            </div>
        </div>
    </form>
</div>

src/StsServerIdentity/Views/Shared/_ValidationSummary.cshtml
@using StsServerIdentity.Resources
@inject LocService SharedLocalizer
@if (ViewContext.ModelState.IsValid == false)
{
    <div class="alert alert-danger">
        <strong>Error</strong>
        <div asp-validation-summary="All" class="danger"></div>
    </div>
}